apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: yaoyingying-
resources:
  - wordpress
  - mysql
  - redis

patchesStrategicMerge:
  - patch.yaml

vars:
  - name: WORDPRESS_SERVICE
    objref:
      kind: Service
      name: wordpress
      apiVersion: v1
  - name: MYSQL_SERVICE
    objref:
      kind: Service
      name: mysql
      apiVersion: v1
